twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: ~
    globals:
        languageIso:
            fr: Français
            en: English
            de: Deutsch
            es: Español
            it: Italiano
            pt: Portugês Brasileiro
            ru: Русский
            ko: 한국어
            cn: 简体中文
        brutAffixes:
            - bolstering
            - fortified
            - necrotic
            - raging
            - sanguine
            - skittish
            - encrypted
            - teeming
            - tyrannical
            - volcanic
            - bursting
            - grievous
            - explosive
            - quaking
            - prideful
            - inspiring
            - spiteful
            - storming
            - tormented
